ClaroGrandesSuperficies/Models/Security/Accounts.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Core.Models.Security
{
	public class Accounts
	{
		public Guid? Id { get; set; }
		public string UserName { get; set; }
		public string Password { get; set; }
		public string[] Roles { get; set; }
        public Guid[] PointOfAtention { get; set; }
	}
}

ClaroGrandesSuperficies/Controllers/AccountsController.cs
using ClaroGrandesSuperficies.Models;
using ClaroGrandesSuperficies.Models.SendEmail;
using Core.Models.Security;
using iTextSharp.text.pdf;
using Syncfusion.Pdf.Parsing;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;




namespace ClaroGrandesSuperficies.Controllers
{
    public class AccountsController : Controller
    {

        private ContextModel db = new ContextModel();
        // GET: Accounts
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(AccountsViewModel avm)
        {

            AccountsModel am = new AccountsModel();
            Accounts ResultUser = am.Login(avm.Accounts.UserName, avm.Accounts.Password);
            if (string.IsNullOrEmpty(avm.Accounts.UserName) || string.IsNullOrEmpty(avm.Accounts.Password) || ResultUser == null)
            {
                ViewBag.Error = "Usuario o contraseña incorrectos";
                return View("index");
            }
            // get user data for the session.
            SessionPersister.UserName = avm.Accounts.UserName;
            SessionPersister.Id = ResultUser.Id;
            SessionPersister.PointOfCare = ResultUser.PointOfAtention;
            if (SessionPersister.PointOfCare.ToList().Count == 1)
            {
                SessionPersister.CurrentPointOfCare = SessionPersister.PointOfCare.FirstOrDefault();
            }

            return RedirectToAction("Home", "Sales", null);

        }

        public ActionResult Logout()
        {
            SessionPersister.UserName = string.Empty;
            SessionPersister.Id = null;
            SessionPersister.PointOfCare = null;
            SessionPersister.CurrentPointOfCare = null;
            return View("index");
        }



        //public ActionResult Create()
        //{
        //    var users = db.Users.Where(x => x.Status).ToList();

        //    return View(users);
        //}

        //[HttpPost]
        //public JsonResult Create(HttpPostedFileBase File, string Email)
        //{

        //    try
        //    {

        //        if (File != null)
        //        {
        //            List<int> Pages = new List<int>();
        //            List<string> documents = db.Users.Where(x => x.Status).Select(x => x.Document).ToList();

        //            var newFilename = File.FileName;
        //            string guid = Guid.NewGuid().ToString();
        //            newFilename = $"Nómina_{guid}.pdf";


        //            //Eliminamos los archivos del directorio.
        //            //string directory = Path.Combine(Server.MapPath("~/File"));
        //            //DeleteFiles(directory);

        //            var extension = Path.GetExtension(File.FileName);
        //            if (extension != ".pdf")
        //            {
        //                return Json(new { status = 404, message = "Archivo con extención no válida" }, JsonRequestBehavior.AllowGet);

        //            }

        //            // Guardamos el nuevo archivo.   
        //            string path = Path.Combine(Server.MapPath("~/File"), Path.GetFileName(newFilename));
        //            File.SaveAs(path);

        //            // Proceso para buscar por número de documento del usuario.

        //            for (int j = 0; j < documents.Count; j++)
        //            {                     

        //                string textToSearch = documents[j].Trim().ToString();
                        
        //                // Leyendo el documento.
        //                StringBuilder text = new StringBuilder();
        //                PdfReader pdfReader = new PdfReader(path);
        //                for (int i = 1; i <= pdfReader.NumberOfPages; i++)
        //                {
        //                    iTextSharp.text.pdf.parser.ITextExtractionStrategy strategy = new iTextSharp.text.pdf.parser.SimpleTextExtractionStrategy();
        //                    string currentText = iTextSharp.text.pdf.parser.PdfTextExtractor.GetTextFromPage(pdfReader, i, strategy);
        //                    currentText = Encoding.UTF8.GetString(ASCIIEncoding.Convert(Encoding.Default, Encoding.UTF8, Encoding.Default.GetBytes(currentText)));

        //                    var pageText = currentText.ToString();

        //                    var exists = pageText.Contains(textToSearch);                            

        //                    if (exists)
        //                    {
        //                        var pagina = (i);
        //                        Pages.Add(pagina);
        //                    }
        //                }

        //                pdfReader.Close();

        //            }

        //            PdfLoadedDocument loadedDocument = new PdfLoadedDocument(path);

        //            #region CODIGO_COMENTADO_VERSION_ANTERIOR.
        //            //Remove the first page in the PDF document
        //            //var indexx = Pages[0].Split(',');
        //            //var index = Pages[0].Split(',');
        //            //var total_pages = loadedDocument.Pages.Count;

        //            //var duplicateExists = index.GroupBy(n => n).Any(g => g.Count() > 1);

        //            //if (duplicateExists)
        //            //{
        //            //    return Json(new { status = 404, message = "Está ingresando páginas duplicadas" }, JsonRequestBehavior.AllowGet);

        //            //}

        //            //if (!SearchPage(index, total_pages))
        //            //{
        //            //    return Json(new { status = 404, message = "La página no existe" }, JsonRequestBehavior.AllowGet);

        //            //}

        //            // Ordenamos la lista de páginas.

        //            #endregion

        //            Pages.Sort();

        //            // Eliminamos las páginas encontradas.
        //            for (int i = 0; i < Pages.Count; i++)
        //            {
        //                var page = Pages[i];
        //                loadedDocument.Pages.RemoveAt(page - (i + 1));
        //            }


        //            loadedDocument.Save(path);
        //            loadedDocument.Dispose();
        //            loadedDocument.Close();

        //            //Envío de correo
        //            SendEmail(path, Email);
        //            return Json(new { status = 200, ruta = "File/" + newFilename }, JsonRequestBehavior.AllowGet);
        //        }

        //        return Json(new { status = 500 }, JsonRequestBehavior.AllowGet);

        //    }
        //    catch (Exception ex)
        //    {
        //        return Json(new { status = 500, message = "No se ha podido crear el archivo" });
        //    }

        //}

        public bool SearchPage(string[] index, int total_pages)
        {
            // Obeniendo la página mayor del array.
            int max = int.Parse(index[0]);

            for (int i = 0; i < index.Length; i++)
            {
                if (int.Parse(index[i]) > max)
                {
                    max = int.Parse(index[i]);
                }
            }

            if (max > total_pages)
            {
                return false;

            }
            return true;
        }


        public void SendEmail(string path, string email)
        {

            var correo = new _Correo()
            {
                ServerName = "mail.uno27.com",
                port = "25",
                senderEmailId = "GS@uno27.com",
                senderPassword = "GS@uno27.com"
            };
            var bodyMessage = string.Empty;
            var mensaje = "Archivo nómina.";
            var correoEnvio = email;

            bodyMessage = "<!DOCTYPE html> <html lang='en'> <head> <meta charset='UTF-8'> <title>Nómina</title> </head> <body><p>" + mensaje + "</p><body></html>";
            Email.EnviarCorreoElectronico(correoEnvio, bodyMessage, "ARCHIVO DE NÓMINA", correo, path);

        }

        private void DeleteFiles(string pathFiles)
        {


            DirectoryInfo di = new DirectoryInfo(pathFiles);


            foreach (FileInfo fi in di.GetFiles())
            {
                var fullPath = $"{pathFiles}\\{ fi.Name}";



                System.IO.File.SetAttributes(fullPath, FileAttributes.Normal);
                System.IO.File.Delete(fullPath);


            }


        }


        public ActionResult AccessDenied()
        {
            return View();
        }

     
    }
}

ClaroGrandesSuperficies/Controllers/UsersController.cs
using ClaroGrandesSuperficies.Models;
using Core.Models.Security;
using Core.Models.User;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace ClaroGrandesSuperficies.Controllers
{

    public class UsersController : Controller
    {
        private ContextModel db = new ContextModel();



        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Document,Names")] User user)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    user.Id = Guid.NewGuid();
                    user.Status = true;
                    db.Users.Add(user);
                    db.SaveChanges();
                    return RedirectToAction("Create", "DeleteFiles", new { Message = 1 });
                }
                catch (Exception)
                {

                    throw;
                }

            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Document,Names,Status")] User user, string Status)
        {

            try
            {
                var userEdit = db.Users.Where(x => x.Id == user.Id).FirstOrDefault();
                userEdit.Status = Status == "1" ? true : false;  
                userEdit.Document = user.Document;
                userEdit.Names = user.Names;

                db.Entry(userEdit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Create", "DeleteFiles", new { Message = 2 });
               
            }
            catch (Exception)
            {

                throw;
            }


        }



        public ActionResult Delete(Guid id)
        {
            try
            {
                if (id == null)
                {
                    return HttpNotFound();
                }
                var user = db.Users.Where(x => x.Id == id).FirstOrDefault();
                user.Status = false;
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Create", "DeleteFiles", new { Message = 3 });

            }
            catch (Exception)
            {

                throw;
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }




    }
}

ClaroGrandesSuperficies/Views/Accounts/AccessDenied.cshtml
@{
    ViewBag.Title = "Index";
}



    <div class="container py-5">
        <div class="row">
            <div class="col-md-2 text-center">
                <p><i class="fa fa-exclamation fa-5x"></i><br />Status Code: 403</p>
            </div>
            <div class="col-md-10">
                <h3>OPPSSS!!!! Lo siento...</h3>
                <p>Lo siento,No tienes acceso a esta pagina  por razones de seguridad y de datos sensibles.<br />por favor regresa a la pagina anterior para que sigas Revisando.</p>
                <a class="btn btn-danger" href="javascript:history.back()">Regresar</a>
            </div>
        </div>
    </div>

    <div id="footer" class="text-center">
        &copy;Uno27 2018, Todos los derechos reservados.
    </div>

ClaroGrandesSuperficies/Views/Accounts/Create.cshtml
@model IEnumerable<Core.Models.User.User>



<style>
    thead {
        background-color: #545b62;
        color: white;
    }
</style>

<div class="box box-danger">
    <div class="box-body">
        <div class="container">
            <div class="box-header with-border">
                <p class="input-group-addon alert text-center"><b>GENERACIÓN DE ARCHIVO</b> </p>
            </div><br />

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="row">
                <div class="col-md-6">
                    <button type="button" class="btn btn-info" data-toggle="modal" data-target=".bd-example-modal-lg">Ver Listado de usuarios a Eliminar del Pdf</button>
                </div>
            </div><br />

            <div class="row">
                <div class="col-md-6">
                    <span><strong>Nombre del Archivo</strong></span>
                    <input type="file" class="form-control check_verificar" id="file_pdf" data-nombre="Archivo" required />
                </div>
                <div class="col-md-6">
                    <span><strong>Correo de destino</strong></span>
                    <input type="email" id="email" class="form-control check_verificar" />
                </div>
            </div>


            <div class="row mt-3">
                <div class="col">
                    <a href="#" download id="download" style="display:none"></a>
                    <input type="button" value="Crear" id="btn_createLog" class="btn btn-info btn-block" />
                </div>
            </div>

        </div><br />
    </div>
</div>


<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="box box-danger">
                <div class="box-body">
                    <div class="container">
                        <div class="box-header with-border">
                            <p class="input-group-addon alert text-center"><b>LISTADO DE USUARIOS A ELIMINAR DEL PDF</b> </p>
                        </div><br />

                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-6">
                                    @Html.ActionLink("Crear Nuevo", "Create", "Users", null, new { @class = "btn btn-xs btn-info" })
                                </div>
                            </div><br />

                            <table id="tabla" class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>
                                            Documento
                                        </th>
                                        <th>
                                            Nombre
                                        </th>
                                        <th>
                                            Estado
                                        </th>
                                        <th>Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Document)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Names)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Status)
                                            </td>
                                            <td>
                                                @Html.ActionLink("Editar", "Edit", "Users", new { id = item.Id }, new { @class = "btn btn-xs btn-primary" })
                                                @Html.ActionLink("Eliminar", "Delete", new { id = item.Id }, new { @class = "btn btn-xs btn-danger" })
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary btn-block" data-dismiss="modal">Close</button>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>




@section Scripts{
    <script src="~/Scripts/downloadFile.js"></script>
}

ClaroGrandesSuperficies/Views/Accounts/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@model  Core.Models.Security.AccountsViewModel

<div class="box box-danger">
	<div class="box-header with-border">
		<h3 class="box-title">Ingresar</h3>
	</div><!-- /.box-header -->
	<div class="box-body">
		<div class="row">
			<div class="col-md-12">
				@using (Html.BeginForm("Login", "Accounts", FormMethod.Post))
				{

					<div class="form-group">
						<label class="control-label col-md-2">Usuario</label>
						<div class="col-md-10">
							@Html.EditorFor(model => model.Accounts.UserName, new { htmlAttributes = new { @class = "form-control" } })
						</div>
					</div>
					<div class="form-group">
                        <br />  
						<label class="control-label col-md-2">contraseña</label>
						<div class="col-md-10">
							@Html.PasswordFor(model => model.Accounts.Password, new { @class = "form-control" })
						</div>
					</div>
					<div class="form-group">
						<label class="control-label col-md-2"></label>
						<div class="col-md-10">
                            <br />
							<input type="submit"	 name="send" value="Ingresar" class="btn btn-success" />
							@if (ViewBag.Error != null) {
								<div class="alert alert-danger">@ViewBag.Error</div>
							}
						</div>
					</div>


				}
			</div>
		</div>

	</div>
</div>